"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core_dup3.ipynb.

# %% auto 0
__all__ = ['tag_pill']

# %% ../nbs/00_core_dup3.ipynb 89
def tag_pill(tag_name, selected=False):
    link = f"/blog?tags={tag_name}"  # you'll need logic to add/remove from current selection
    cls = [ButtonT.primary if selected else ButtonT.secondary, ButtonT.sm, "rounded-lg"]
    return Button(tag_name, cls=cls, hx_get=link, **hx_attrs())
