"""Fill in a module description here"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core_dup1.ipynb.

# %% auto #0
__all__ = ['tag_pill', 'get_post_tags', 'get_posts']

# %% ../nbs/00_core_dup1.ipynb #33280a01
def tag_pill(tag_name, selected=False):
    link = f"/blog?tags={tag_name}"  # you'll need logic to add/remove from current selection
    cls = [ButtonT.primary if selected else ButtonT.secondary, ButtonT.sm, "rounded-lg"]
    return Button(tag_name, cls=cls, hx_get=link, **hx_attrs())

# %% ../nbs/00_core_dup1.ipynb #4f213634
def get_post_tags(post_id: int):
    query = """
    SELECT name FROM tags WHERE id IN (SELECT tag_id FROM post_tags WHERE post_id=?)
    """
    tag_name_dicts = pdb.q(query, [post_id])
    tag_names = [name['name'] for name in tag_name_dicts]
    return tag_names

# %% ../nbs/00_core_dup1.ipynb #c057a87b
def get_posts(n: Union[int, None]=None, tags: Union[List, None] = None):
    if tags:
        place_holders = ','.join('?'*len(tags))
        post_query = f"SELECT DISTINCT post_id FROM post_tags WHERE tag_id IN (SELECT id FROM tags WHERE name IN ({place_holders}))"
        post_ids = pdb.q(post_query, tags)
        post_ids = [post['post_id'] for post in post_ids]
        if post_ids:
            place_holders = ','.join('?'*len(post_ids))
            post_query = f"id IN ({place_holders})"
            posts = list(posts_t.rows_where(post_query, post_ids, limit=n, order_by="-created"))
        else:
            posts = []
    else:
        posts = list(posts_t.rows_where(order_by="-created", limit=n))

    if posts:
        result = [dict(r) for r in posts]
        for p in result: p['created'] = datetime.fromisoformat(p['created']) if isinstance(p['created'], str) else p['created']
        for p in result: p['tags'] = get_post_tags(p['id'])
        return result
    return []
