# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/05_blog_v5.ipynb.

# %% auto #0
__all__ = ['yt_hdrs', 'AppState', 'create_database_tables', 'create_post_database', 'create_app', 'route', 'register_routes',
           'logout', 'intro', 'hx_attrs', 'hx_link', 'is_logged_in', 'navbar', 'x_icon', 'social_link', 'footer',
           'layout', 'slug_exists', 'get_slug', 'blogpost', 'index', 'get_tags', 'get_post_tags', 'get_posts',
           'tag_pill', 'tag_filter', 'tag_badge', 'decode_tag_str', 'sentinal', 'blog', 'get_more_posts',
           'get_post_image', 'check_if_admin', 'post_card', 'add_post', 'process_upload', 'get', 'save_pending',
           'load_pending', 'clear_pending', 'do_upload', 'post', 'rewrite_image_paths', 'convert_obsidian_images',
           'load_md_file', 'about_content', 'about', 'EnhancedRenderer', 'strava_embed', 'process_strava_embeddings',
           'process_komoot_embed', 'process_obsidian_images', 'process_you_tube_embed', 'sitemap']

# %% ../nbs/05_blog_v5.ipynb #6a381e96
from fastlite import Database
from pathlib import Path
from datetime import datetime, timedelta
import my_blog.config as config
from urllib.parse import quote, unquote
from fasthtml.common import *
from monsterui.all import *
from fasthtml_auth import AuthManager
from fasthtml.jupyter import *
import re
import frontmatter

# %% ../nbs/05_blog_v5.ipynb #3a049b85
@dataclass
class AppState:
    pdb: Database # for managing posts
    posts_t: Table
    tags_t: Table
    post_tags_t: Table
    auth: AuthManager
    db: Database # For managing users and authorising access

# %% ../nbs/05_blog_v5.ipynb #1b911c99
def create_database_tables(pdb: Database # database to save posts and all associated tag tables
    ): 

    class Posts:
        id: int # primary key
        title: str # post title
        slug: str # unique slug based upon title
        content: str # The post content in markdown
        created: datetime # date and time created
        updated: datetime # date and time modified
        published: bool # is post published
        excerpt: str # short summary of the post
        private: bool # post only visible to logged in users

    posts = pdb.create(Posts, pk='id', defaults={'published': False, 'private':False}, transform=True)
    posts.create_index(['slug'], unique=True, if_not_exists=True)

    class Tags:
        id: int # primary key
        name: str # unique
    
    tags = pdb.create(Tags, pk='id', transform=True)
    tags.create_index(['name'], unique=True, if_not_exists=True)

    class PostTags:
        post_id: int # foreign key > posts.id
        tag_id: int # foreign key > tags.id
    
    post_tags = pdb.create(PostTags, pk=['post_id', 'tag_id'], transform=True)

    


# %% ../nbs/05_blog_v5.ipynb #95894ac6
def create_post_database(db_path: str # path to posts database
                        )-> Database: # Creates all the required database tables if they don't already exist
    pdb = Database(db_path)
    pdb.execute("PRAGMA foreign_keys = ON")
    create_database_tables(pdb)
    return pdb

# %% ../nbs/05_blog_v5.ipynb #85b497d5
yt_hdrs = (
    Script(f"""
function loadYouTube(el) {{
    var tmpl = document.getElementById('yt-template');
    var iframe = tmpl.content.firstElementChild.cloneNode(true);
    var id = el.getAttribute('data-video-id');
    iframe.src = "https://www.youtube.com/embed/" + id + "?autoplay=1&origin={config.ORIGIN}";
    el.replaceWith(iframe);
}}
"""),
    Template(
        Iframe(
            frameborder="0",
            allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share",
            referrerpolicy="strict-origin-when-cross-origin",
            allowfullscreen=True,
            cls="w-full aspect-video rounded-lg my-6",
            title="YouTube video player"
            ),
            id="yt-template"
    ),
)

# %% ../nbs/05_blog_v5.ipynb #6be13b13
def create_app():
    # Create databases and apps, return these within and AppState class.
    # Once created then create the server with srv = serve()
    # Add the routes with rt = app.route
    pdb = create_post_database(config.POSTS_DB_PATH)
    posts_t = pdb.t.posts
    tags_t = pdb.t.tags
    post_tags_t = pdb.t.post_tags
    # Initialize auth database
    auth = AuthManager(
        db_path=str(config.USERS_DB_PATH),
        config={
            'allow_registration': config.ALLOW_REGISTRATION,
            'public_paths': ['/', '/about', r'/blog.*', r'/post.*', '/googleada316577537ad2b.html', '/sitemap.xml'],  # Let anybody see the site apart from the admin and auth routes
            'login_path': '/auth/login',
        }
    )
    db = auth.initialize()
    # Set db password
    admin = auth.get_user(config.ADMIN_USERNAME)
    if admin and config.ADMIN_PASSWORD: auth.user_repo.update(admin.id, password=config.ADMIN_PASSWORD, email=config.ADMIN_EMAIL)
    beforeware = auth.create_beforeware()
    hdrs = (*Theme.blue.headers(highlightjs=True), Script(src="https://unpkg.com/hyperscript.org@0.9.12"),
        Script(src="https://www.googletagmanager.com/gtag/js?id=G-DP7YB96KHH", async_=True),
        Script("window.dataLayer = window.dataLayer || []; function gtag(){dataLayer.push(arguments);} gtag('js', new Date()); gtag('config', 'G-DP7YB96KHH');"),
        *yt_hdrs,
        Link(rel="icon", type="image/png", href="/static/image/john_pixelated.png"))
    app = FastHTML(
        before=beforeware,
        secret_key=config.SECRET_KEY,
        hdrs=hdrs,
        exts='ws'  # Enable WebSocket support
    )
    config.STATIC_DIR.mkdir(parents=True, exist_ok=True)
    app.mount("/static", StaticFiles(directory=str(config.STATIC_DIR)), name="static")
    auth.setup_oauth(app=app, redirect_url=config.OAUTH_REDIRECT, allow_oauth_user_create=False)
    auth.register_routes(app, include_admin=True)
    state = AppState(
        pdb=pdb,
        posts_t=posts_t,
        tags_t=tags_t,
        post_tags_t=post_tags_t,
        auth=auth,
        db=db
    )
    return app, state

# %% ../nbs/05_blog_v5.ipynb #962ff0b2
# Route collection for deferred registration
_routes = []

def route(path=None):
    """Decorator to collect routes without registering them immediately.
    Use @route('/path') or @route() for function-name-based paths."""
    def decorator(f):
        _routes.append((path, f))
        return f
    if callable(path):  # @route without parens
        f, path = path, None
        _routes.append((path, f))
        return f
    return decorator

# %% ../nbs/05_blog_v5.ipynb #21d398cd
def register_routes(app):
    """Register all collected routes with the app."""
    for path, handler in _routes:
        if path:
            app.route(path)(handler)
        else:
            app.route(handler)

# %% ../nbs/05_blog_v5.ipynb #491704df
@route(f"/admin/logout")
def logout(sess):
    """ Overwrite logout route from fasthtml_auth to return users to home page after logging out
    """
    print("MY LOGOUT CALLED")
    sess.clear()
    return Response(status_code=200, headers={"HX-Redirect": "/"})


# %% ../nbs/05_blog_v5.ipynb #7e9d1570
def intro():
    return Article(
        H3("Welcome to my Blog Site", cls="text-2xl font-semibold mb-4"),
        Div(cls="text-base gap-1 text-muted-foreground leading-relaxed space-y-4")(
        P("I created this site to keep a record of things I am interested in.  As such it will largely cover motorhome trips, cycling events and routes that I have done and enjoyed, coding and software development activities I am interested in or engaged with, and technology that I think is worth looking at.  You can find out more about me on my ", hx_link("About", "/about"), " page"),

        P("This site is developed using fastHTML and the Solveit platform, both technologies developed by Jeremy Howard and ",A('Answer.ai', href='https://answer.ai', target="_blank", rel="noopener noreferrer", cls="text-primary underline"), " The desgn was originally based upon the site of ", A('Jack Hogan.', href='https://jackhogan.net/', target="_blank", rel="noopener noreferrer", cls="text-primary underline"), "but has evolved to be database driven for both users and posts, as well as to incorporate infinite scroll amongst other things"

        " See my latest blog posts below or find the full list on my ", hx_link("Blog", "/blog"), " page, where posts can be readily filtered by topic.")
        )
    )


# %% ../nbs/05_blog_v5.ipynb #e502d740
def hx_attrs(target="#main-content"): return dict(hx_target=target, hx_push_url="true", hx_swap="innerHTML show:window:top")

def hx_link(txt, href, cls="text-primary underline", target="#main-content", **kw):
    # Utility function to configure the update of the target (by default the #main-content) using hx_get. Falls back to html if not htmx
    return A(txt, href=href, hx_get=href, cls=cls, **hx_attrs(target), **kw)

# %% ../nbs/05_blog_v5.ipynb #d09ae8e2
def is_logged_in(req):
    auth_user_name = req.scope.get('session', {}).get('auth')
    return True if auth_user_name else False


# %% ../nbs/05_blog_v5.ipynb #1f69321c
def navbar(req: Request):
    # Check if logged in user
    logged_in = is_logged_in(req)
    if logged_in:
        log_link = hx_link(UkIcon("user"), "/admin/logout") 
    else:
        log_link = A(UkIcon('log-in'), href="/auth/login", cls="uk-button uk-button-default uk-button-xs")
    brand = A(Img(src="/static/image/john_pixelated.png", alt="John Richmond", cls="w-6 h-6 rounded-full"), Span("John Richmond "), href="/", hx_get="/", cls="flex items-center gap-2 text-lg font-bold", **hx_attrs())
    links = Div(hx_link("About", "/about"), hx_link("Blog", "/blog"), log_link, cls="flex gap-4 items-center")
    return Nav(Div(brand, links, cls="flex items-center gap-2 justify-between p-4"), cls="border rounded-lg shadow bg-background")

# %% ../nbs/05_blog_v5.ipynb #991ad9c7
def x_icon(): return Svg(ft_hx("path", d="M12.6.75h2.454l-5.36 6.142L16 15.25h-4.937l-3.867-5.07-4.425 5.07H.316l5.733-6.57L0 .75h5.063l3.495 4.633L12.601.75Zm-.86 13.028h1.36L4.323 2.145H2.865z"), width=20, height=20, fill="currentColor", viewBox="0 0 16 16", aria_hidden="true")



# %% ../nbs/05_blog_v5.ipynb #6c3ca569
def social_link(icon, href, **kw):
    kw = dict(rel="nofollow noindex") if k == "mail" else dict(target="_blank", rel="noopener noreferrer")
    return A(x_icon() if k == "twitter" else UkIcon(icon, width=20, height=20), href=href, cls="hover:text-primary transition-colors", target="_blank", rel="noopener noreferrer", **kw)

def social_link(k, v):
    ext = dict(rel="nofollow noindex") if k == "mail" else {} if k == "rss" else dict(target="_blank", rel="noopener noreferrer")
    return A(x_icon() if k == "twitter" else UkIcon(k, width=20, height=20), href=v, aria_label=k.title(), cls="hover:text-primary transition-colors", **ext)


def footer():
    links = dict(twitter="https://x.com/@johnWrichmond", youtube="https://youtube.com/@confusedjohn46a", github="https://github.com/fromLittleAcorns")
    icons = Div(*[social_link(k, v) for k, v in links.items()], social_link("mail", "mailto:confusedjohn46@gmail.com"), cls="flex justify-center gap-6 text-muted-foreground")
    return Footer(Divider(), icons, cls="max-w-2xl mx-auto px-6 mt-auto mb-6")

# %% ../nbs/05_blog_v5.ipynb #e31ffc1b
def layout(req, *content, htmx, title=None):
    ''' title here is used to set the browser tab label in the <head> section and will not be visible on the page.  The article title is appended into the main content and shows below the navbar
    '''
    if htmx and htmx.request: return (Title(title), *content)
    main = Main(*content, cls='w-full max-w-2xl mx-auto px-6 py-8 space-y-8', id="main-content")
    return Title(title), Div(Div(navbar(req), cls='max-w-2xl mx-auto px-4 mt-4'), main, footer(), cls="flex flex-col min-h-screen")

# %% ../nbs/05_blog_v5.ipynb #80c4cbeb
def slug_exists(slug):
    if bool(list(state.posts_t.rows_where("slug = ?", [slug], limit=1))):
        return list(state.posts_t.rows_where("slug = ?", [slug], limit=1))[0]['id']
    else:
        return False

# %% ../nbs/05_blog_v5.ipynb #954e2a1d
def get_slug(title):
    slug = title.lower().replace(" ", "-")
    slug = ''.join(c for c in slug if c.isalnum() or c == '-')[:60]
    return slug


# %% ../nbs/05_blog_v5.ipynb #91dae216
@route('/blog/{slug}')
def blogpost(htmx, req, slug: str):
    is_admin = check_if_admin(req)
    logged_in = is_logged_in(req)
    row = state.posts_t.rows_where("slug = ?", [slug], limit=1)
    p = next((dict(r) for r in row), None)
    if not p:
        return layout(req, H2("Not Found"), P("Post not found."), title="Not Found", htmx=htmx)
    if p.get('private') and not logged_in:
        return layout(req, H2("Not Found"), P("Please login to access this post."), title="Private post", htmx=htmx)
    p['created'] = datetime.fromisoformat(p['created']) if isinstance(p['created'], str) else p['created']
    content = render_md(p['content'], renderer=EnhancedRenderer)
    image_base = f"/static/image/post_images/{slug}"
    content = process_obsidian_images(content, image_base=image_base)
    content = process_strava_embeddings(content)
    content = process_komoot_embed(content)
    content = process_you_tube_embed(content)
    admin_btns = Div(
        A("Edit", href=f'/admin/edit/{slug}', cls="uk-btn uk-btn-default uk-btn-xs"),
        # Button("Delete", hx_post=f"/admin/delete/{p['slug']}", hx_confirm="Delete this post?", 
        #    cls=["uk-btn uk-btn-default uk-btn-xs"]),
        Button("Delete", hx_post=f"/admin/delete/{slug}", hx_confirm="Delete this post?", 
            hx_swap="innerHTML", cls="uk-btn uk-btn-default uk-btn-xs"),
        A("Download", href=f"/admin/download/{p['slug']}", cls=[ButtonT.default, "uk-btn-xs"]),
        cls='flex gap-1'
    ) if is_admin else Div()
    return layout(req, H1(p['title'], cls="text-3xl font-bold mb-2"), Span(p['created'].strftime('%B %d, %Y'), cls="text-muted-foreground text-sm mb-8 block"), content, 
    admin_btns, Script(src="https://strava-embeds.com/embed.js"), title=p['title'], htmx=htmx)

# %% ../nbs/05_blog_v5.ipynb #a1c2acd2
@route
def index(req, htmx):
    logged_in = is_logged_in(req)
    posts = get_posts(n=6, logged_in=logged_in)
    items = [A(H3(p['title']), P(p['excerpt'], cls="text-muted-foreground"), Span(p['created'].strftime('%d %b %Y'), cls="text-sm text-muted-foreground"), href=f"/blog/{p['slug']}", hx_get=f"/blog/{p['slug']}", cls="block border-b pb-4 hover:bg-muted/50 transition-colors", **hx_attrs()) for p in posts]
    content = Div(*items, cls="space-y-4") if items else P("No posts yet.", cls="text-muted-foreground")
    return layout(req, (intro(), Divider(), Section(H3("Latest Posts", cls="text-xl font-semibold mb-4"), content)), title="Welcome to my Blog", htmx=htmx)

# %% ../nbs/05_blog_v5.ipynb #514f8dc1
def get_tags(tags_tbl):
    tags = [row.name for row in tags_tbl()]
    return tags


# %% ../nbs/05_blog_v5.ipynb #273bf4f9
def get_post_tags(post_id: int):
    query = """
    SELECT name FROM tags WHERE id IN (SELECT tag_id FROM post_tags WHERE post_id=?)
    """
    tag_name_dicts = state.pdb.q(query, [post_id])
    tag_names = [name['name'] for name in tag_name_dicts]
    return tag_names

# %% ../nbs/05_blog_v5.ipynb #31e79c0d
def get_posts(
        n: Union[int, None]=None, # number of posts to load
        tags: Union[List, None] = None, # list of tags
        logged_in: bool=False, # is user logged in
        offset: Union [int, None]=None # where to start to load posts once ordered
        )->list: # list of posts
    if tags:
        place_holders = ','.join('?' * len(tags))
        private_posts_query = '' if logged_in else 'AND p.private = False '
        query = f"""
            SELECT DISTINCT p.* FROM posts p
            JOIN post_tags pt ON p.id = pt.post_id
            JOIN tags t ON pt.tag_id = t.id
            WHERE t.name IN ({place_holders}) AND p.published = True {private_posts_query}
            ORDER BY p.created DESC
        """
        if n: query += f" LIMIT {n}"
        if offset: query += f" OFFSET {offset}"
        posts = state.pdb.q(query, tags)
    else:
        posts = list(state.posts_t.rows_where("published = ? AND (private = False OR ?)", [True, logged_in], 
            order_by="created DESC", limit=n, offset=offset))
        posts = [dict(r) for r in posts]

    for p in posts:
        p['created'] = datetime.fromisoformat(p['created']) if isinstance(p['created'], str) else p['created']
        p['tags'] = get_post_tags(p['id'])
    return posts

# %% ../nbs/05_blog_v5.ipynb #88bb55a3
def tag_pill(tag_name, selected_tags):
    if tag_name in selected_tags:
        new_tags = selected_tags - {tag_name}
        selected = True
    else:
        new_tags = selected_tags | {tag_name}
        selected = False
    link = f"/blog?tags={','.join(new_tags)}" if new_tags else "/blog"
    cls = [ButtonT.primary if selected else ButtonT.secondary, ButtonT.sm, "rounded-lg"]
    return Button(tag_name, cls=cls, hx_get=link, **hx_attrs("#posts-list"))

# %% ../nbs/05_blog_v5.ipynb #d34579b6
def tag_filter(selected):
    # Return a div containing all of the tags and their selection status. We also need a button to clear the current selection
    selected: set # a set containing the names of the selected tags
    tags = get_tags(state.tags_t)
    tag_pills = [tag_pill(tag_name, selected) for tag_name in tags]
    clear_btn = Button("X Clear", cls=[ButtonT.default, ButtonT.sm, "rounded-lg"], hx_get="/blog", **hx_attrs("#posts-list"))
    return Div(P("Filter: "), *tag_pills, clear_btn, cls="flex flex-wrap gap-2 items-center", id="tag-filter")

# %% ../nbs/05_blog_v5.ipynb #36362347
def tag_badge(name):
    return Span(name, cls="text-xs px-2 py-1 rounded bg-muted")

# %% ../nbs/05_blog_v5.ipynb #82972f75
def decode_tag_str(tag_str: str):
    # Decode a string containing a list of items with comma separation, needed to decode a list sent as a url parameter. 
    # Returns a set of unique items
    selected = {unquote(t.strip()) for t in (tag_str or '').split(',') if t.strip()}
    return selected

# %% ../nbs/05_blog_v5.ipynb #6ef80d65
def sentinal(
        n:int, # number of posts to load
        offset:int=None, # where to start the load
        tags: str=None # a list of active tags separated by commas
        )->Div: # Div to add to the end of the list of posts to act as a sentinal
    " Create a div to add to the end of the posts on the blog. When it becomes visible then it activates the load of more posts"
    get_str = f"/loadmore?offset={offset}&n={n}"
    if tags: 
        get_str += f"&tags={tags}"
    sentinal = Div(
        hx_get=get_str,    
        hx_trigger="intersect once",
        hx_swap="outerHTML",
        hx_target="this"
    )
    return sentinal

# %% ../nbs/05_blog_v5.ipynb #a29d4fec
@route
def blog(htmx, req, tags:str=None):
    logged_in = is_logged_in(req)
    posts_to_load = 10
    # selected is a SET of the name of the selected tags
    selected = decode_tag_str(tags)
    filtered = get_posts(n=posts_to_load, tags=selected, logged_in=logged_in)
    tag_filter_div = tag_filter(selected)
    items = [post_card(p, req) for p in filtered]
    if len(items) == posts_to_load:
        items.append(sentinal(offset=posts_to_load, n=posts_to_load, tags=tags))
    post_content = Div(*items, cls="space-y-2", id="posts-list") if items else P("No posts yet.", cls="text-muted-foreground", id="posts-list")
    if htmx and htmx.target == "posts-list":
        tag_filter_div.attrs['hx-swap-oob'] = 'true'
        return post_content, tag_filter_div
    return layout(req, H2("Blog"), tag_filter_div, Divider(cls=('my-2')), post_content, title="Blog", htmx=htmx)

# %% ../nbs/05_blog_v5.ipynb #3851743c
@route("/loadmore")
def get_more_posts(req, n: int, offset: int, tags: str=None):
    logged_in = is_logged_in(req)
    selected_tags = decode_tag_str(tags)
    posts = get_posts(n=n, tags=selected_tags, logged_in=logged_in, offset=offset)
    items = [post_card(p, req) for p in posts]
    if len(items) == n:
        new_sentinal = sentinal(offset=offset+n, n=n, tags=tags)
        return (*items, new_sentinal)
    return (*items,)



# %% ../nbs/05_blog_v5.ipynb #4df85229
def get_post_image(p):
    # check post content for image (/static/image/post_images/slug/*)
    # If image found then load a thumbnail of it
    img_ptn = r"!\[\[([^|\]]+?)(?:\|[^\]]+)?\]\]"
    imgs = re.findall(img_ptn,p["content"])
    img = imgs[0] if len(imgs)>0 else None
    if img:
        img_path = Path(img)
        slug = get_slug(p['title'])
        img_path = Path(config.POST_IMAGE_DIR) / Path(slug) / img_path
        return img_path
    else:
        return None

# %% ../nbs/05_blog_v5.ipynb #7f1ad1ed
def check_if_admin(req):
    sess = req.scope.get('session', {})
    auth_username = sess.get('auth')
    user = state.auth.get_user(auth_username) if auth_username else None
    check_admin = is_admin = user and user.role == 'admin'
    return check_admin

# %% ../nbs/05_blog_v5.ipynb #62ecd6cc
def post_card(p, req):
    "Post summary card with optional admin controls"
    is_admin = check_if_admin(req)
    img_url = get_post_image(p)
    slug = p['slug']
    link_attrs = dict(href=f"/blog/{slug}", hx_get=f"/blog/{slug}", **hx_attrs())
    admin_btns = Div(
        A("Edit", href=f'/admin/edit/{slug}', cls="uk-btn uk-btn-default uk-btn-xs"),
        # Button("Delete", hx_post=f"/admin/delete/{p['slug']}", hx_confirm="Delete this post?", 
        #    cls=["uk-btn uk-btn-default uk-btn-xs"]),
        Button("Delete", hx_post=f"/admin/delete/{slug}", hx_confirm="Delete this post?", 
            hx_target="#main-content", hx_swap="innerHTML", 
            cls="uk-btn uk-btn-default uk-btn-xs"),
        A("Download", href=f"/admin/download/{p['slug']}", cls=[ButtonT.default, "uk-btn-xs"]),
        cls='flex gap-1'
    ) if is_admin else Div()
    return Div(cls="flex gap-4 p-3 -mx-3 rounded-lg border-b pb-4 hover:bg-muted/50 hover:shadow-lg transition-all")(
        Div(cls="flex-1")(
            A(H3(p['title']), P(p['excerpt'], cls="text-muted-foreground"), **link_attrs),
            Div(cls='flex justify-between items-center mt-2')(
                Div(Span(p['created'].strftime('%d %b %Y'), cls="text-sm text-muted-foreground mr-2"),
                    *[tag_badge(tag) for tag in p["tags"]], cls="flex items-center gap-2 flex-wrap"),
                admin_btns)),
        A(Img(src=img_url, cls="max-w-36 h-auto object-contain rounded"), **link_attrs) if img_url else None)

# %% ../nbs/05_blog_v5.ipynb #b0f1fe99
def add_post(title, content, excerpt="", tags=None, published=True, created=None, updated=None, slug: str=None, private: bool=False):
    if not slug:
        slug = get_slug(title)
    posts = state.pdb.t.posts
    tags_tbl = state.pdb.t.tags
    post_tags = state.pdb.t.post_tags
    now = datetime.now()
    post_id = slug_exists(slug)
    if post_id:
        post = posts.update(dict(id=post_id, title=title, slug=slug, content=content, excerpt=excerpt,
                                 created=created or now, updated=now, published=published, private=private))
        state.pdb.execute("DELETE FROM post_tags WHERE post_id = ?", [post_id])
    else:
        post = posts.insert(dict(title=title, slug=slug, content=content, excerpt=excerpt,
                                 created=created or now, updated=updated or now, published=published, private=private))
    post_id = post['id'] if isinstance(post, dict) else post.id
    if tags:
        if isinstance(tags, str): tags = [tags]
        for tag in tags:
            existing = list(tags_tbl.rows_where("name = ?", [tag], limit=1))
            if existing: tag_id = existing[0]['id']
            else:
                result = tags_tbl.insert(dict(name=tag))
                tag_id = result['id'] if isinstance(result, dict) else result.id
            if not list(post_tags.rows_where("post_id = ? AND tag_id = ?", [post_id, tag_id])):
                post_tags.insert(dict(post_id=post_id, tag_id=tag_id))
    return post_id

# %% ../nbs/05_blog_v5.ipynb #f75481a2
def process_upload(content: bytes, filename: str, slug:str=None, overwrite: bool=False):
    file_path = Path(filename)
    if file_path.suffix == '.md':
        try:
            md_text = content.decode('utf-8')
            post = frontmatter.loads(md_text)
            title = post.metadata['title']
            tags = post.metadata['tags']
            excerpt = post.metadata['excerpt']
            created = post.metadata.get('created')
            updated = post.metadata.get('updated')
            private = post.metadata.get('private', False)
            # Get the slug from the post if it exists, if not then create a slug
            slug = post.metadata.get('slug') or get_slug(title)
            if not overwrite and slug_exists(slug):
                return 'confirm', "Post already exists. Overwrite?", slug
            try:
                if overwrite:
                    add_post(slug=slug, title=title, content=post.content, excerpt=excerpt, tags=tags, updated=updated, private=private)
                else:
                    add_post(title=title, content=post.content, excerpt=excerpt, tags=tags, created=created, updated=updated, private=private)
            except Exception as e:
                print(f'Error on save attempt: {e}')
                return False, f"Unable to save post: {e}", None
            return True, "Post saved", slug
        except Exception as e:
            return False, f"Error processing md: {type(e).__name__}: {e}", None
    elif file_path.suffix in ['.jpg', '.png', '.jpeg', '.tif', '.svg']:
        path_to_save = Path(config.POST_IMAGE_DIR) / Path(slug) / file_path.name
        path_to_save.parent.mkdir(parents=True, exist_ok=True)
        path_to_save.write_bytes(content)
        return True, f"File {path_to_save.name} saved", slug
    else:
        return False, f"Unknown file type {file_path.suffix}", slug

# %% ../nbs/05_blog_v5.ipynb #ec27541d
@route('/admin/upload')
def get(htmx):
    # Create file upload form for the post
    return Div(Div(A('Cancel', href='/', cls=f"{ButtonT.secondary} px-4 py-2"), Upload("Upload Button!", id='upload1', multiple=True), cls='flex gap-2'),
               Div(id='upload-message'),
               Form(
                UploadZone(DivCentered(Span("Upload Zone"), UkIcon("upload")), id='upload2', accept=['.md', '.jpg', '.jpeg', 'png', 'svg', 'gif'], multiple=True,
                hx_target='#upload-message', hx_trigger='change', hx_post='/admin/upload', hx_swap='innerHTML', hx_encoding="multipart/form-data"),
                cls='space-y-4')
    )

# %% ../nbs/05_blog_v5.ipynb #ffe86d0d
def save_pending(slug: str, md_name: str, md_content: bytes, images: list[tuple[str, bytes]]):
    """Save md content and images to temp storage keyed by slug.
    images is a list of (filename, bytes) tuples."""
    import pickle
    Path(f'/tmp/pending_{slug}.pkl').write_bytes(pickle.dumps({'name': md_name, 'md': md_content, 'images': images}))

# %% ../nbs/05_blog_v5.ipynb #4d043c1a
def load_pending(slug: str):
    """Returns (md_content, images) or None if not found."""
    import pickle
    p = Path(f'/tmp/pending_{slug}.pkl')
    if not p.exists(): return None
    data = pickle.loads(p.read_bytes())
    return data['name'], data['md'], data['images']

# %% ../nbs/05_blog_v5.ipynb #9fb636a4
def clear_pending(slug: str):
    Path(f'/tmp/pending_{slug}.pkl').unlink(missing_ok=True)

# %% ../nbs/05_blog_v5.ipynb #67efba69
def do_upload(md_files, img_files, slug: str=None, overwrite: bool=False):
    results = []
    for name, content in md_files:
        success, message, slug_from_title = process_upload(content, name, overwrite=overwrite)
        if not slug:
            slug = slug_from_title
        if success == 'confirm':
            save_pending(slug, name, content, img_files)
            return 'confirm', slug
        results.append((name, success, message))
    for name, content in img_files:
        success, message, _ = process_upload(content, name, slug=slug)
        results.append((name, success, message))
    header = ["Name", "Success", "Message"]
    return 'done', TableFromLists(header, [[r[0], r[1], r[2]] for r in results])

# %% ../nbs/05_blog_v5.ipynb #f5cc3377
@route('/admin/upload')
def post(upload2: list[UploadFile]):
    files = [(f.filename, f.file.read()) for f in upload2]
    md_files = [(n, c) for n, c in files if n.endswith('.md')]
    img_files = [(n, c) for n, c in files if not n.endswith('.md')]
    status, result = do_upload(md_files, img_files)
    if status == 'confirm':
        slug = result
        # return a confirmation dialog - result is the slug
        return Div(P("Post already exists. Overwrite?"),
                   Button("Yes, overwrite", hx_post=f"/admin/upload/overwrite?slug={slug}", hx_target="#upload-message", hx_swap="innerHTML"),
                   Button("Cancel", cls=ButtonT.secondary, hx_get="/admin/upload", hx_target="#upload-message", hx_swap="innerHTML"))
    return Div(H2("Upload results"), result)

# %% ../nbs/05_blog_v5.ipynb #461bf991
@route('/admin/upload/overwrite')
def post(slug: str):
    pending = load_pending(slug)
    if not pending: return Alert("No pending upload found", cls=AlertT.warning)
    md_name, md_content, img_files = pending
    status, result = do_upload([(md_name, md_content)], img_files, slug=slug, overwrite=True)
    clear_pending(slug)
    return Div(H2("Upload results"), result)

# %% ../nbs/05_blog_v5.ipynb #de66363e
def rewrite_image_paths(content: str, slug: str) -> str:
    # img_ptn = r"!\[.*?\]\((/static/image/post_images/[^)]+)\)"
    img_ptn = r"(!\[.*?\])\(([^/)]+\.(jpg|jpeg|png|gif|svg))\)"
    replacement = rf"\1(/static/image/post_images/{slug}/\2)"
    return re.sub(img_ptn, replacement, content, flags=re.IGNORECASE)

# %% ../nbs/05_blog_v5.ipynb #1ee544b2
def convert_obsidian_images(content: str, image_base: str = "/static/image/about") -> str:
    """Convert Obsidian ![[image.ext]] syntax to standard markdown ![](/path/image.ext)"""
    # pattern = r'!\[\[([^\]]+\.(jpg|jpeg|png|gif|svg))\]\]'
    pattern = r'!\[\[([^|\]\n]+\.(?:jpg|jpeg|png|gif|svg))(?:[\\|][^\]]+)?\]\]'
    replacement = rf'![]({image_base}/\1)'
    return re.sub(pattern, replacement, content, flags=re.IGNORECASE)

def load_md_file(path: str, image_base: str = None) -> str:
    """Load markdown file, optionally converting Obsidian image syntax"""
    content = Path(path).read_text()
    if image_base:
        content = convert_obsidian_images(content, image_base)
    return content

# %% ../nbs/05_blog_v5.ipynb #c59a1712
def about_content():
    md = load_md_file(config.STATIC_DIR / "content/About.md", image_base="/static/image/about")
    return render_md(md)

# %% ../nbs/05_blog_v5.ipynb #cd6f7060
@route
def about(req, htmx):
    return layout(req, about_content(),title="About Me", htmx=htmx)

# %% ../nbs/05_blog_v5.ipynb #b49fbacf
from mistletoe import Document
from monsterui.franken import FrankenRenderer

# %% ../nbs/05_blog_v5.ipynb #71f9e091
class EnhancedRenderer(FrankenRenderer):
    def _is_external(self, url):
        return url.startswith(('http://', 'https://', '//'))

    def render_link(self, token):
        target = self.escape_url(token.target)      
        title = f' title="{self.escape_html(token.title)}"' if token.title else ''
        inner = self.render_inner(token)

        # Determine if we need the new tab attributes
        extra_attrs = ' target="_blank" rel="noopener noreferrer"' if self._is_external(target) else ''

        return f'<a href="{target}"{extra_attrs}{title}>{inner}</a>'

    def render_autolink(self, token):
        target = self.escape_url(token.target)
        inner = self.render_inner(token)
        
        # Autolinks are almost always external, but we'll check anyway
        extra_attrs = ' target="_blank" rel="noopener noreferrer"' if self._is_external(target) else ''
        
        return f'<a href="{target}"{extra_attrs}>{inner}</a>'

    def render_paragraph(self, token):
        if self._suppress_ptag_stack[-1]: return self.render_inner(token)
        return f'<p class="text-lg leading-relaxed mb-6">{self.render_inner(token)}</p>'

# %% ../nbs/05_blog_v5.ipynb #ab467a70
def strava_embed(activity_id: str):
    return Div(cls="strava-embed-placeholder", data_embed_type="activity", data_embed_id=activity_id, data_style="standard")

# %% ../nbs/05_blog_v5.ipynb #ac1c56c6
def process_strava_embeddings(page: NotStr):
    page = str(page)
    # Pattern to match {{strava:ID}} possibly wrapped in <p> tags
    pattern_placeholder = r'(<p[^>]*>)?\s*\{\{strava:(\d+)\}\}\s*(</p>)?'
    
    def replace_strava(match):
        activity_id = match.group(2)
        return to_xml(strava_embed(activity_id))
    
    page = re.sub(pattern_placeholder, replace_strava, page)
    return NotStr(page)

# %% ../nbs/05_blog_v5.ipynb #c71cf180
def process_komoot_embed(page: NotStr):
    page = str(page)
    pattern = r'(<p[^>]*>)?\s*\{\{komoot:(\d+)\|([A-Za-z0-9]+)(?:\|(gallery|classic))?\}\}\s*(</p>)?'
    
    def replace_komoot(match):
        tour_id = match.group(2)
        share_token = match.group(3)
        layout = match.group(4) or 'classic'
        if layout == 'gallery':
            src = f"https://www.komoot.com/tour/{tour_id}/embed?share_token={share_token}&layout=gallery&gallery=1"
            height = "640"
        else:
            src = f"https://www.komoot.com/tour/{tour_id}/embed?share_token={share_token}&layout=classic&profile=1"
            height = "700"
        return f'<iframe src="{src}" width="100%" height="{height}" frameborder="0" scrolling="no"></iframe>'
    
    page = re.sub(pattern, replace_komoot, page)
    return NotStr(page)

# %% ../nbs/05_blog_v5.ipynb #ffe15f8f
def process_obsidian_images(page: NotStr, image_base: str) -> NotStr:
    page = str(page)
    pattern = new3 = r'''!\[\[(?P<image>[^\]]+\.(jpg|jpeg|png|gif|svg)) # Image part, must be present
(?:\|(?P<size1>\d+))? # First size dimension (with leading pipe symbol (optional)
(?:x(?P<size2>\d+))? # Second size dimension (with leading x)
(?:\|(?P<location>left|right|center))?
\]\] # End of image (must be present)
'''
    
    for match in re.finditer(pattern, page, re.MULTILINE + re.VERBOSE):
        m = match.groupdict()
        
        # 1. Build src path
        src = f"{image_base}/{m['image']}"
        
        # 2. Build style string from size1, size2, location
        styles = []
        if m['size1']:
            styles.append(f"width: {m['size1']}px")
        if m['size2']:
            styles.append(f"height: {m['size2']}px")
        if m['location'] == 'center':
            styles.append("display: block; margin: auto")
        elif m['location'] == 'right':
            styles.append("float: right; margin-left: 1rem")
        elif m['location'] == 'left':
            styles.append("float: left; margin-right: 1rem")
        
        style_str = "; ".join(styles)
        
        # 3. Build img tag and replace
        img_tag = f'<img src="{src}" style="{style_str}">'
        page = page.replace(match.group(0), img_tag)
    
    return NotStr(page)

# %% ../nbs/05_blog_v5.ipynb #7ccb6366
def process_you_tube_embed(page: NotStr):
        page = str(page)
        pattern_vb  = r'''
(<p[^>]*?>)? # find and capture <p> if it is there.  Allows for intermediate characters after p but only up to >
(\s*)?(<a[^>]*?>) # Find the <a and any href and class values up to the first >.  Optional
https?://(?:www\.)?(?:youtu\.be/|youtube\.com/watch\?v=)(?P<index>[A-Za-z0-9_-]{11}) # Catch the index of the youtube video
(</a>)? # Catch the terminating a tag if it exists
(</p>)? # Catch the terminating p tag if it exists
'''
        for match in re.finditer(pattern_vb, page, re.MULTILINE+re.VERBOSE):
            video_id = match['index']
            placeholder = Div(
                Img(src=f"https://img.youtube.com/vi/{video_id}/hqdefault.jpg",
                        cls="w-full aspect-video rounded-lg my-6"),
                cls="relative cursor-pointer",
                onclick="loadYouTube(this)",
                data_video_id=video_id  # becomes data-video-id in the HTML
                )
            placeholder = to_xml(placeholder)
            page = page.replace(match.group(0), placeholder)
        return NotStr(page)

# %% ../nbs/05_blog_v5.ipynb #b47e6237
@route('/sitemap.xml')
def sitemap():
    slug_list = state.pdb.q("""SELECT p.slug FROM posts p WHERE p.private = False ORDER BY p.created""")
    slug_list = [slug['slug'] for slug in slug_list]
    base = "https://blog.therichmond4.co.uk"
    static_urls = ["/", "/about", "/blog"]
    urls = static_urls + [f"/blog/{slug}" for slug in slug_list]
    xml = '<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
    xml += "\n".join(f"  <url><loc>{base}{u}</loc></url>" for u in urls)
    xml += "\n</urlset>"
    return Response(xml, media_type="application/xml")


